(function () {
  const QUOTES = [
    { text: "You can tell the greatness of a man by what makes him angry.", author: "Abraham Lincoln" },
    { text: "Genius is the power of carrying the feelings of childhood into the powers of manhood.", author: "Samuel Taylor" },
    { text: "Most of us aren't defeated in one decisive battle. We are defeated one tiny, seemingly insignificant surrender at a time that chips away at who we should really be.", author: "Jocko Willink" },
    { text: "The end of all things is at hand; therefore be self-controlled and sober-minded for the sake of your prayers.", author: "1 Peter 4:7" },
    { text: "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.", author: "Marcus Aurelius" },
    { text: "Don’t raise your voice. Improve your argument.", author: "Desmond Tutu" },
    { text: "No man is free who is not master of himself.", author: "Epictetus" },
    { text: "I am not afraid of storms, for I am learning how to sail my ship.", author: "Louisa May Alcott" },
    { text: "The world will ask you who you are, and if you do not know, the world will tell you.", author: "Carl Jung" },
    { text: "If you don't like something, change it. If you can't change it, change your attitude. Don't complain.", author: "Maya Angelou" },
    { text: "Always listen to experts. They'll tell you what can't be done, and why. Then do it.", author: "Robert A. Heinlein" },
    { text: "I have had lots of troubles in my life, most of which never happened.", author: "Mark Twain" },
    { text: "I mean to make myself a man, and if I succeed in that, I shall succeed in everything else.", author: "James A. Garfield" },
    { text: "There is a destiny which makes us brothers; none goes his way alone. All that we send into the lives of others comes back into our own.", author: "Edwin Markham" },
    { text: "Anyone can carry his burden, however heavy, until nightfall. Anyone can do his work, however hard, for one day. Anyone can live sweetly, patiently, lovingly, purely, until the sun goes down. And this is all that life really means.", author: "Robert Louis Stevenson" },
    { text: "There is no finer sensations in life that which comes with victory over one’s self. Go forward to a goal of inward achievement, brushing aside all your old internal enemies as you advance.", author: "Vash Young" },
    { text: "When you have exhausted all possibilities, remember this: you haven't.", author: "Thomas Edison" },
    { text: "Our greatest weapon against stress is our ability to choose one thought over another.", author: "William James" },
    { text: "Nothing is so strong as gentleness, nothing so gentle as real strength.", author: "Saint Francis de Sales" },
    { text: "Within you is a stillness and a sanctuary to which you can retreat at any time and be yourself.", author: "Hermann Hesse" },
    { text: "Write it on your heart that every day is the best day in the year. He is rich who owns the day, and no one owns the day who allows it to be invaded with fret and anxiety.", author: "Ralph Waldo Emerson" },
    { text: "My code of life and conduct is simply this: work hard, play to the allowable limit, disregard equally the good and bad opinion of others, never do a friend a dirty trick… live the moment to the utmost of its possibilities… and be satisfied with life always but never with one's self.", author: "George Jean Nathan" },
    { text: "Most people get ahead during the time that others waste.", author: "Henry Ford" },
    { text: "One who fears failure limits his activities. Failure is only the opportunity to more intelligently begin again.", author: "Henry Ford" },
    { text: "Whatever we plant in our subconscious mind and nourish with repetition and emotion will one day become reality.", author: "Earl Nightingale" },
    { text: "Independence Day: freedom has its life in the hearts, the actions, the spirit of men and so it must be daily earned and refreshed – else like a flower cut from its life-giving roots, it will wither and die.", author: "Dwight D. Eisenhower" },
    { text: "Nothing will ever be attempted if all possible objections must first be overcome.", author: "Samuel Johnson" },
    { text: "Often people won't specify their goals because they don't like to specify conditions for failure.", author: "Jordan Peterson" },
    { text: "Never underestimate the ability of a small group of dedicated people to change the world. Indeed, it is the only thing that ever has.", author: "Margaret Mead" },
    { text: "What you do speaks so loudly that I cannot hear what you say.", author: "Ralph Waldo Emerson" },
    { text: "Beware what you set your heart upon. For it surely shall be yours.", author: "Ralph Waldo Emerson" },
    { text: "Imagination was given to man to compensate him for what he isn't. A sense of humor was provided to console him for what he is.", author: "Horace Walpole" },
    { text: "Keep doing good deeds long enough and you'll probably turn out a good man in spite of yourself.", author: "Louis Auchincloss" },
    { text: "God's providence is not a code to be decyphered, it's a plan to be trusted", author: "John Piper" },
    { text: "Adversity draws men together and produces beauty and harmony in life's relationships, just as the cold of winter produces ice-flowers on the window-panes, which vanish with the warmth.", author: "Søren Kierkegaard" },
    { text: "In any moment of decision, the best thing you can do is the right thing, the next best thing is the wrong thing, and the worst thing you can do is nothing.", author: "Theodore Roosevelt" },
    { text: "Even if I knew that tomorrow the world would go to pieces, I would still plant my apple tree.", author: "Martin Luther" },
    { text: "God is able to make all grace abound to you, so that having all sufficiency in all things at all times, you may abound in every good work.", author: "2 Corinthians 9:8" },
    { text: "The trick for human thriving in the face of suffering and malevolence is strength, not protection.", author: "Jordan Peterson" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "It’s better to be boldly decisive and risk being wrong than to agonise at length and be right too late.", author: "Marilyn Moats Kennedy" },
    { text: "Above all, don't lie to yourself. The man who lies to himself and listens to his own lie comes to a point that he cannot distinguish the truth within him, or around him, and so loses all respect for himself and for others. And having no respect he ceases to love.", author: "Fyodor Dostoevsky" },
    { text: "We either make ourselves miserable, or we make ourselves strong. The amount of work is the same.", author: "Carlos Castaneda" },
    { text: "Not grace to bar what is not bliss, Nor flight from all distress, but this: The grace that orders our trouble and pain, And then, in the darkness, is there to sustain.", author: "John Piper" },
    { text: "Face the demands of life voluntarily. Respond to a challenge, instead of bracing for a catastrophe.", author: "Jordan Peterson" },
    { text: "Conflict delayed is conflict multiplied.", author: "Jordan Peterson" },
    { text: "When you have something to say, silence is a lie.", author: "Jordan Peterson" },
    { text: "People don't really repress the things they don't want to face, they just fail to unpack them.", author: "Jordan Peterson" },
    { text: "The greatest mistake you can make in life is to be continually fearing you will make one.", author: "Elbert Hubbard" },
    { text: "You should never grade evils, for if one is the worst, then you might be tempted to kinship with the least.", author: "Captain Victor Saltzpyre, Warhammer" },
    { text: "Be courteous to all, but intimate with few, and let those few be well tried before you give them your confidence.", author: "George Washington" },
    { text: "Be not angry that you cannot make others as you wish them to be, since you cannot make yourself as you wish to be.", author: "Thomas à Kempis" },
    { text: "Do not be too timid and squeamish about your reactions. All life is an experiment. The more experiments you make the better.", author: "Ralph Waldo Emerson" },
    { text: "The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails.", author: "William Arthur Ward" },
    { text: "Error never shows itself in its naked reality, in order not to be discovered. On the contrary, it dresses elegantly, so that the unwary may be led to believe that it is more truthful than truth itself.", author: "Irenaeus of Lyons" },
    { text: "All get what they want; they do not always like it.", author: "C.S. Lewis" },
    { text: "The price good men pay for indifference to public affairs is to be ruled by evil men.", author: "Plato" },
    { text: "If you look for truth, you may find comfort in the end; if you look for comfort you will not get either comfort or truth only soft soap and wishful thinking to begin, and in the end, despair.", author: "C.S. Lewis" },
    { text: "How few there are who have courage enough to own their faults, or resolution enough to mend them.", author: "Benjamin Franklin" },
    { text: "How much time he gains who does not look to see what his neighbour says or does or thinks, but only at what he does himself, to make it just and holy.", author: "Marcus Aurelius" },
    { text: "Impatience breeds anxiety, fear, discouragement and failure. Patience creates confidence, decisiveness, and a rational outlook, which eventually leads to success.", author: "Brian Adams" },
    { text: "The measure of success is not whether you have a tough problem to deal with, but whether it is the same problem you had last year.", author: "John Foster Dulles" },
    { text: "Then, when you wake up in the middle of the night and the doubts crowd in, you have some defense: 'For all my flaws, at least I am doing this. At least I am taking care of myself. At least I am of use to my family, and to the other people around me. At least I am moving, stumbling upward, under the load I have determined to carry.'", author: "Jordan Peterson" },
    { text: "Quietude, which some men cannot abide because it reveals their inward poverty, is as a palace of cedar to the wise, for along its hallowed courts the King in his beauty deigns to walk.", author: "Charles Spurgeon" },
    { text: "When we carry out our 'religious duties,' we are like people digging channels in a waterless land, in order that when at last the water comes, it may find them ready.", author: "C.S. Lewis" },
    { text: "The whole world looks different when he sees her. Her voice reminds him of something he has been trying to remember all his life, and ten minutes’ casual chat with her is more precious than all the favors that all the other women in the world could grant.", author: "C.S. Lewis" },
    { text: "Fathering is not something perfect men do, but something that perfects the man.", author: "Frank Pittman" },
    { text: "A true soldier fights not because he hates what is in front of him, but because he loves what is behind him.", author: "G.K. Chesterton" },
    { text: "They that know have grown afraid to speak. That is why sorrows that used to purify now only fester.", author: "C.S. Lewis" },
    { text: "If he experiences winning, he is not happy for long; but if he plays with the hope of winning, he can be happy for a long time by being both diverted (by playing) and deluded (believing he’d be truly happy if he won). Success is the sure spoiler. We are happy only climbing the mountain, not staying peacefully on the summit; only chasing the fox, not catching it; only courting, not marrying; only traveling, not arriving; only fighting wars, not keeping a boring peace.", author: "Peter Kreeft" },
    { text: "A lie can get around the world before the truth can get its shoes on.", author: "Charles Spurgeon" },
    { text: "Faced with a choice between changing one’s mind and proving there is no need to do so, almost everyone gets busy with the proof.", author: "J.K. Galbraith" },
    { text: "I don’t like that man. I must get to know him better.", author: "Abraham Lincoln" },
    { text: "The release of atom power has changed everything except our way of thinking… the solution to this problem lies in the heart of mankind. If only I had known, I should have become a watchmaker.", author: "Albert Einstein" },
    { text: "The best fighter is never angry.", author: "Lao Tzu" },
    { text: "This time, like all times, is a very good one, if we but know what to do with it.", author: "Ralph Waldo Emerson" },
    { text: "Nothing fixes a thing so intensely in the memory as the wish to forget it.", author: "Michel de Montaigne" },
    { text: "How do you want to feel at the end of today? What do you need to do now, so you can feel this way?", author: "James Clear" },
    { text: "You never know what worse luck your bad luck has saved you from.", author: "Cormac McCarthy" },
    { text: "Behold, Thy servant, fleeing from his Lord, and obtaining a shadow.", author: "St. Augustine" },
    { text: "Thou has made us for Thyself and our heart is restless, until it finds its rest in Thee.", author: "St. Augustine" },
    { text: "When we make dancing and movies the test of spirituality, we are guilty of substituting a cheap morality for a genuine one.", author: "R.C. Sproul" },
    { text: "Sometimes fear does not subside and one must choose to do it afraid.", author: "Elisabeth Elliot" },
    { text: "Mental Health is dedication to reality at all costs.", author: "M. Scott Peck" },
    { text: "To lack feelings is to be dead, but to act on every feeling is to be a child.", author: "Dalinar, The Way of Kings" },
    { text: "It’s hard to see the label when you’re in the jar.", author: "" },
    { text: "The purpose of a story-teller is not to tell you how to think, but to give you questions to think upon.", author: "Wit, The Way of Kings" },
    { text: "No man is more unhappy than he who never faces adversity. For he is not permitted to prove himself.", author: "Seneca" },
    { text: "Fasting is, as much as lies in us, an imitation of the angels, a contemning of things present, a school of prayer, a nourishment of the soul, a bridle of the mouth, an abatement of concupiscence: it mollifies rage, it appeases anger, it calms the tempests of nature, it excites reason, it clears the mind, it disburdens the flesh, it chases away night-pollutions, it frees from head-ache. By fasting, a man gets composed behaviour, free utterance of his tongue, right apprehensions of his mind.", author: "John Chrysostom" },
    { text: "I shall open my eyes and ears. Once every day I shall simply stare at a tree, a flower, a cloud, or a person. I shall not then be concerned at all to ask what they are but simply be glad that they are. I shall joyfully allow them the mystery of what Lewis calls their “divine, magical, terrifying, and ecstatic” existence.", author: "Clyde Kilby" },
    { text: "He loves Thee too little, who loves anything together with Thee, which he loves not for Thy sake.", author: "Augustine" },
  ];

  const textEl = document.getElementById("quote-text");
  const authorEl = document.getElementById("quote-author");
  if (!textEl || !authorEl) return;

  const pick = QUOTES[Math.floor(Math.random() * QUOTES.length)];
  textEl.textContent = pick.text;
  authorEl.textContent = pick.author ? "— " + pick.author : "";
})();
